### ISSUE TITLE
Alternative OpenAI API Key Environment Variable

### ISSUE THREAD

**Issue by domainexpert** [abhishek9sharma/sarathi#22]
It may be a good idea to prioritize reading from, maybe an environment variable called SARATHI_OPENAI_API_KEY, so that we can use a token key specifically for Sarathi. I think people may have OPENAI_API_KEY defined for other uses.

**Comment by abhishek9sharma** [comment]
https://github.com/abhishek9sharma/sarathi/pull/25 should address this. Also I have added the option for user if they want to generate commit and not ammend. All covered in this above PR. Let me know in case you have any comments

**Comment by domainexpert** [comment]
Thank you @abhishek9sharma. #25 looks good to me.
